name: ETL semanal - IndiCES

on:
    schedule:
        - cron: "0 14 * * 1" #todos los Lunes a las 11 am
    workflow_dispatch: #disparo manual desde GitHub

jobs:
  etl:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Setup R
          uses: r-lib/actions/setup-r@v2
          with:
            cache-version: 1
        
        - name: Ejecutar ETL
          run: Rscript etl/pipeline-core.R

        - name : Copiar RDS a app/
          run: |
            mv data/processed/indicadores.rds app/data/processed/indicadores.rds
            mv data/processed/datos.rds app/data/processed/datos.rds
        
        - name: Commit datos actualizados
          run: |
           git config --local user.name "github-actions[bot]"
           git config --local user.email "github-actions[bot]users.noreply.github.com"
           git add data/processed app/data/processed/
           git diff --staged --quiet || git commit -m "etl: actualizar datos $(date +'%Y-%m-%d')"
           git push

        - name: Deploy a shinnyapps.io
          env:
            SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
            SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
            SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
          run: |
            Rscript -e "
              rsconnect::setAccountInfo(
                name = Sys.getenv('SHINYAPPS_ACCOUNT')
                token = Sys.getenv('SHINYAPPS_TOKEN')
                secret = Sys.getenv('SHINYAPPS_SECRET')
                )
                rsconnect::deployApp('app', appName='indicesApp', forceUpdate = TRUE)
            "
      
